#!/usr/bin/python 
import sys
import pygame
import math
 
class CollisionModel:
    'Class for collision detection'
    def CircleTouchesLine(self, A, B, C, r ):
        result.inside = false
        result.tangent = false
        result.intersects = false
        result.enter = nothing
        result.out = nothing
        a = (B.x - A.x) * (B.x - A.x) + (B.y - A.y) * (B.y - A.y)
        b = 2 * ((B.x - A.x) * (A.x - C.x) +(B.y - A.y) * (A.y - C.y))
        cc = C.x * C.x + C.y * C.y + A.x * A.x + A.y * A.y - 2 * (C.x * A.x + C.y * A.y) - r * r
        deter = b * b - 4 * a * cc
        if (deter <= 0 ):
            result.inside = false
        else:
            e = Math.sqrt (deter)
            u1 = ( - b + e ) / (2 * a )
            u2 ( - b - e ) / (2 * a )
            if ((u1 < 0 or u1 > 1) and (u2 < 0 or u2 > 1)):
                if ((u1 < 0 and u2 < 0) or (u1 > 1 and u2 > 1)):
                    result.inside = false
                else:
                    result.inside = true
            else:
 #               if (0 <= u2 and u2 <= 1):
 #			    result.enter=Point.interpolate (A, B, 1 - u2)

 #               if (0 <= u1 and u1 <= 1):
 #                   result.exit=Point.interpolate (A, B, 1 - u1)
                    
                result.intersects = true
                if (result.out != nothing and result.enter != nothing and result.out.equals (result.enter)) :
                    result.tangent = true		
            return result
